#!/usr/bin/env python3
"""
prepare_xbd_cache.py
====================

One-time cache preparation shared by the xBD ResNet-18 experiments.

This script is downstream of src/build_manifest.py.

EXPECTED REPOSITORY LAYOUT
--------------------------

repo/
├── data/
│   ├── train/
│   ├── processed/
│   │   └── tier1/
│   │       ├── pre/
│   │       └── post/
│   └── manifest_train.csv
│
├── src/
│   └── build_manifest.py
│
└── base_train/
    └── ezekiel_resnet18_baseline/
        ├── prepare_xbd_cache.py      <-- THIS FILE
        ├── train_post_resnet18.py
        ├── train_prepost_resnet18.py
        ├── train_prepost_resnet18_plaince.py
        └── cache/                    <-- CREATED HERE

NORMAL USE
----------

After src/build_manifest.py has created data/manifest_train.csv and the
variable-size PRE/POST building crops, run this script from the baseline:

    python prepare_xbd_cache.py

No path arguments are required in the standard repository layout.

The script derives paths from its own file location rather than the terminal's
current working directory.

INPUT
-----

    repo/data/manifest_train.csv

The manifest is expected to contain:

    building_id
    scene_id
    split
    disaster_type
    damage_label
    pre_crop_path
    post_crop_path
    original_bbox
    original_crop_width
    original_crop_height

The crop paths generated by src/build_manifest.py are relative to the data/
directory. Because manifest_train.csv also lives directly in data/, they can
be resolved directly from the manifest location.

OUTPUT
------

    <baseline>/cache/
        ├── pre/
        ├── post/
        └── cache_manifest.csv

The cache manifest uses paths relative to its own directory:

    pre/0000000.png
    post/0000000.png

This keeps the cache portable and avoids embedding usernames, drive letters,
or machine-specific absolute paths.

WHAT THIS SCRIPT DOES
---------------------

1. Loads data/manifest_train.csv.
2. Keeps the four labeled damage classes:
       no-damage
       minor-damage
       major-damage
       destroyed
3. Excludes un-classified rows from this four-class baseline cache.
4. Adds integer targets:
       0 = no-damage
       1 = minor-damage
       2 = major-damage
       3 = destroyed
5. Resolves the PRE and POST crop files referenced by the manifest.
6. Resizes each crop to 224 x 224 using bilinear interpolation.
7. Saves the resized images as lossless PNG files.
8. Writes cache_manifest.csv with relative PRE/POST cache paths.

WHY USE A CACHE?
----------------

The manifest builder preserves variable-size building crops. Resizing those
same images during every training epoch would repeatedly perform identical
CPU/image-processing work.

This script performs that deterministic resize once. Training can then load
ready-to-use 224 x 224 PNGs directly.

The cache includes both PRE and POST crops and is shared by the POST-only and
paired PRE+POST experiments.

THIS SCRIPT DOES NOT TRAIN A MODEL.

OPTIONAL OVERRIDES
------------------

For a non-standard repository layout:

    python prepare_xbd_cache.py --manifest "C:\\path\\to\\manifest_train.csv"

    python prepare_xbd_cache.py --cache-dir "D:\\path\\to\\cache"

Use --rebuild to overwrite existing cache PNGs. If manifest_train.csv changes,
regenerate the cache with --rebuild.
"""

from __future__ import annotations

import argparse
import time
from pathlib import Path

import pandas as pd
from PIL import Image


CLASS_NAMES = [
    "no-damage",
    "minor-damage",
    "major-damage",
    "destroyed",
]

LABEL_MAP = {
    name: index
    for index, name in enumerate(CLASS_NAMES)
}


# ---------------------------------------------------------------------------
# REPOSITORY PATHS
# ---------------------------------------------------------------------------

BASELINE_DIR = Path(__file__).resolve().parent


def find_repo_root(start: Path) -> Path:
    """
    Walk upward until a repository root containing data/ is found.

    This lets the script work even when launched from a different terminal
    directory.
    """
    for parent in [start, *start.parents]:
        if (parent / "data").is_dir():
            return parent.resolve()

    raise SystemExit(
        "Could not locate the repository data/ directory.\n\n"
        "Expected the baseline to be somewhere inside a repository containing:\n"
        "    data/manifest_train.csv\n\n"
        "For a non-standard layout, pass --manifest explicitly."
    )


def default_manifest_path() -> Path:
    repo_root = find_repo_root(BASELINE_DIR)
    return repo_root / "data" / "manifest_train.csv"


DEFAULT_CACHE_DIR = BASELINE_DIR / "cache"


# ---------------------------------------------------------------------------
# ARGUMENTS
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(
        description="Prepare the portable 224 x 224 xBD baseline cache.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help=(
            "Path to manifest_train.csv. "
            "Default: <repo>/data/manifest_train.csv"
        ),
    )

    parser.add_argument(
        "--cache-dir",
        type=Path,
        default=DEFAULT_CACHE_DIR,
        help="Output directory for cache_manifest.csv, pre/, and post/.",
    )

    parser.add_argument(
        "--rebuild",
        action="store_true",
        help=(
            "Overwrite cached PNG files that already exist. Use this to "
            "regenerate the cache after manifest_train.csv changes."
        ),
    )

    return parser.parse_args()


# ---------------------------------------------------------------------------
# HELPERS
# ---------------------------------------------------------------------------

def format_seconds(seconds: float) -> str:
    seconds = int(max(0, round(seconds)))
    hours, remainder = divmod(seconds, 3600)
    minutes, seconds = divmod(remainder, 60)

    if hours:
        return f"{hours}h {minutes:02d}m {seconds:02d}s"

    if minutes:
        return f"{minutes}m {seconds:02d}s"

    return f"{seconds}s"


def resolve_crop_path(raw_path: str, manifest_path: Path) -> Path:
    """
    Resolve a crop path from manifest_train.csv.

    src/build_manifest.py writes paths such as:

        processed/tier1/post/<building_id>.png

    Because manifest_train.csv lives directly inside data/, resolving the path
    relative to manifest_train.csv's parent points to the correct source file.
    """
    raw = Path(str(raw_path))

    if raw.is_absolute():
        candidate = raw.expanduser().resolve()
    else:
        candidate = (
            manifest_path.parent
            / raw
        ).expanduser().resolve()

    if candidate.exists():
        return candidate

    raise FileNotFoundError(
        "A crop referenced by manifest_train.csv could not be found.\n\n"
        f"Manifest value:\n    {raw_path}\n\n"
        f"Resolved path:\n    {candidate}\n\n"
        "Confirm that src/build_manifest.py completed successfully and that "
        "data/processed/ has not been moved independently of the manifest."
    )


def resize_and_save(source: Path, destination: Path) -> None:
    """Resize one crop to 224 x 224 and save it as a lossless RGB PNG."""
    with Image.open(source) as image:
        image = image.convert("RGB")
        image = image.resize(
            (224, 224),
            Image.Resampling.BILINEAR,
        )
        image.save(
            destination,
            format="PNG",
            compress_level=3,
        )


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def main():
    args = parse_args()

    manifest_path = (
        args.manifest.expanduser().resolve()
        if args.manifest is not None
        else default_manifest_path()
    )

    cache_dir = (
        args.cache_dir
        .expanduser()
        .resolve()
    )

    if not manifest_path.exists():
        raise SystemExit(
            "manifest_train.csv was not found.\n\n"
            f"Expected:\n    {manifest_path}\n\n"
            "Run src/build_manifest.py first, or pass --manifest explicitly."
        )

    cache_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    pre_dir = cache_dir / "pre"
    post_dir = cache_dir / "post"

    pre_dir.mkdir(
        parents=True,
        exist_ok=True,
    )
    post_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    print("=" * 80)
    print("xBD 224 x 224 CACHE PREPARATION")
    print("=" * 80)
    print()
    print(f"Manifest:  {manifest_path}")
    print(f"Cache:     {cache_dir}")
    print()

    # -----------------------------------------------------------------------
    # Load and validate the manifest.
    # -----------------------------------------------------------------------

    df = pd.read_csv(
        manifest_path
    )

    required = {
        "building_id",
        "scene_id",
        "damage_label",
        "pre_crop_path",
        "post_crop_path",
    }

    missing = required - set(
        df.columns
    )

    if missing:
        raise SystemExit(
            "manifest_train.csv is missing required columns:\n"
            f"    {sorted(missing)}"
        )

    original_rows = len(df)

    # This cache is intentionally for the four-class damage task.
    df = (
        df[
            df["damage_label"]
            .isin(CLASS_NAMES)
        ]
        .copy()
        .reset_index(drop=True)
    )

    if df.empty:
        raise SystemExit(
            "No four-class examples found in manifest_train.csv."
        )

    df["target"] = (
        df["damage_label"]
        .map(LABEL_MAP)
        .astype(int)
    )

    excluded_rows = (
        original_rows
        - len(df)
    )

    print(f"Manifest rows:           {original_rows:,}")
    print(f"Four-class cache rows:   {len(df):,}")
    print(f"Excluded rows:           {excluded_rows:,}")
    print()

    # -----------------------------------------------------------------------
    # Build the cache.
    # -----------------------------------------------------------------------

    rows = []
    start = time.perf_counter()

    for index, row in df.iterrows():
        cache_id = f"{index:07d}"

        pre_name = f"{cache_id}.png"
        post_name = f"{cache_id}.png"

        pre_out = pre_dir / pre_name
        post_out = post_dir / post_name

        # Resolve both source files BEFORE writing either cache image.
        # A missing source therefore cannot create a partial PRE/POST pair.
        pre_source = resolve_crop_path(
            row["pre_crop_path"],
            manifest_path,
        )

        post_source = resolve_crop_path(
            row["post_crop_path"],
            manifest_path,
        )

        # Write each file only after the complete source pair has been located.
        if args.rebuild or not pre_out.exists():
            resize_and_save(
                pre_source,
                pre_out,
            )

        if args.rebuild or not post_out.exists():
            resize_and_save(
                post_source,
                post_out,
            )

        cache_row = {
            "cache_id": cache_id,
            "building_id": row["building_id"],
            "scene_id": row["scene_id"],
            "damage_label": row["damage_label"],
            "target": int(row["target"]),

            # Relative to cache_manifest.csv.
            "pre_png": f"pre/{pre_name}",
            "post_png": f"post/{post_name}",
        }

        # Preserve source metadata useful to downstream experiments.
        for column in [
            "split",
            "disaster_type",
            "original_bbox",
            "original_crop_width",
            "original_crop_height",
        ]:
            if column in df.columns:
                cache_row[column] = row[column]

        rows.append(
            cache_row
        )

        completed = index + 1

        if (
            completed % 5000 == 0
            or completed == len(df)
        ):
            elapsed = (
                time.perf_counter()
                - start
            )

            rate = (
                completed / elapsed
                if elapsed > 0
                else 0.0
            )

            remaining = (
                len(df)
                - completed
            )

            eta = (
                remaining / rate
                if rate > 0
                else 0.0
            )

            print(
                f"{completed:,}/{len(df):,} | "
                f"{rate:.1f} buildings/s | "
                f"elapsed={format_seconds(elapsed)} | "
                f"ETA={format_seconds(eta)}"
            )

    # -----------------------------------------------------------------------
    # Save cache manifest atomically.
    # -----------------------------------------------------------------------

    cache_manifest = pd.DataFrame(
        rows
    )

    cache_manifest_path = (
        cache_dir
        / "cache_manifest.csv"
    )

    temporary_path = (
        cache_manifest_path
        .with_suffix(".csv.tmp")
    )

    cache_manifest.to_csv(
        temporary_path,
        index=False,
    )

    temporary_path.replace(
        cache_manifest_path
    )

    elapsed = (
        time.perf_counter()
        - start
    )

    # -----------------------------------------------------------------------
    # Completion summary.
    # -----------------------------------------------------------------------

    print()
    print("=" * 80)
    print("CACHE PREPARATION COMPLETE")
    print("=" * 80)
    print()
    print(f"Rows cached: {len(cache_manifest):,}")
    print(f"Total time:  {format_seconds(elapsed)}")
    print()
    print("Damage-label distribution:")

    counts = (
        cache_manifest["damage_label"]
        .value_counts()
        .reindex(
            CLASS_NAMES,
            fill_value=0,
        )
    )

    for label, count in counts.items():
        fraction = (
            100.0
            * count
            / len(cache_manifest)
            if len(cache_manifest)
            else 0.0
        )

        print(
            f"  {label:16s} "
            f"{int(count):8,d} "
            f"({fraction:6.2f}%)"
        )

    print()
    print("Output:")
    print(f"  Manifest:   {cache_manifest_path}")
    print(f"  PRE cache:  {pre_dir}")
    print(f"  POST cache: {post_dir}")


if __name__ == "__main__":
    main()
